export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL= 'FETCH_USERS_FAIL';

export const FETCH_POSTS_LIST_START = 'FETCH_POSTS_LIST_START';
export const FETCH_POSTS_LIST_SUCCESS = 'FETCH_POSTS_LIST_SUCCESS';
export const FETCH_POSTS_LIST_FAIL= 'FETCH_POSTS_LIST_FAIL';