/* USERS */

export const FETCH_USERS_START = "FETCH_USERS_START";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";

export const FETCH_USER_BY_ID_START = "FETCH_USER_BY_ID_START";
export const FETCH_USER_BY_ID_SUCCESS = "FETCH_USER_BY_ID_SUCCESS";
export const FETCH_USER_BY_ID_FAIL = "FETCH_USER_BY_ID_FAIL";

/* Posts */

export const FETCH_POSTS_LIST_START = "FETCH_POSTS_LIST_START";
export const FETCH_POSTS_LIST_SUCCESS = "FETCH_POSTS_LIST_SUCCESS";
export const FETCH_POSTS_LIST_FAIL = "FETCH_POSTS_LIST_FAIL";

export const FETCH_POSTS_BY_USER_START = "FETCH_POSTS_BY_USER_START";
export const FETCH_POSTS_BY_USER_SUCCESS = "FETCH_POSTS_BY_USER_SUCCESS";
export const FETCH_POSTS_BY_USER_FAIL = "FETCH_POSTS_BY_USER_FAIL";
